[alembic]
# Alembic Configuration

# path to migration files
# the URL will be filled from environment or config
sqlalchemy.url = 

# location of migration scripts (relative to project root)
script_location = alembic

# use relative paths, so the created migration scripts
# files will be independent of the current working path you run alembic from.
file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current directory
prepend_sys_path = .

# timezone to use when rendering the date within the migration file as well as the filename.
# string value is passed to the constructor of datetime.datetime. The string labels
# can also be passed by creating a new datetime.datetime object, as follows
# from datetime import datetime
# datetime.tz = datetime.timezone.utc
# timezone =


# max length of characters to apply to the
# "slug" field in the revision file
# (defaults to 40)
# truncate_slug_length = 40


# set multiple lines of kw args to use with the
# create_engine() call (note: this is an SQLAlchemy >= 1.1
# feature; this setting is only used in an 'sqlalchemy.url'
# is presented elsewhere):
# sqlalchemy.echo_pool = true
# sqlalchemy.pool_recycle = 3600
# sqlalchemy.pool_pre_ping = true

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
